### ISSUE TITLE
Plugin is not a function with Babel 6.x

### ISSUE THREAD

**Issue by ovaris** [oliviertassinari/babel-plugin-react-remove-properties#2]
.babelrc:
```
{
  "presets": ["stage-1", "es2015", "react"],
  "plugins": [
    ["babel-plugin-transform-es2015-classes", { "loose": true }],
    "transform-proto-to-assign",
    "react-remove-properties"
  ]
}
```
I'm using latest Babel 6.2.0,
And I get this error when doing webpack:
```
TypeError: Plugin is not a function
    at module.exports (/Users/ollivaris/programming/nextgen/node_modules/babel-plugin-react-remove-properties/lib/index.js:6:10)
    at Function.memoisePluginContainer (/Users/ollivaris/programming/nextgen/node_modules/babel-core/lib/transformation/file/options/option-manager.js:127:13)
    at Function.normalisePlugin (/Users/ollivaris/programming/nextgen/node_modules/babel-core/lib/transformation/file/options/option-manager.js:161:32)
    at /Users/ollivaris/programming/nextgen/node_modules/babel-core/lib/transformation/file/options/option-manager.js:197:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/ollivaris/programming/nextgen/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
    at OptionManager.mergeOptions (/Users/ollivaris/programming/nextgen/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
    at OptionManager.addConfig (/Users/ollivaris/programming/nextgen/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/Users/ollivaris/programming/nextgen/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (/Users/ollivaris/programming/nextgen/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
```

Any idea what's wrong in my setup?

**Comment by ovaris** [comment]
Okay Its probably because of change Plugin API, more info here http://babeljs.io/blog/2015/10/29/6.0.0/

**Comment by oliviertassinari** [comment]
Thanks, for the links, I should fix this!

**Comment by ovaris** [comment]
I was about to submit pr but failed to make test pass:(

**Comment by oliviertassinari** [comment]
Could you submit the PR so that I can help to fix the test issue?

**Comment by ovaris** [comment]
Sure, please check https://github.com/oliviertassinari/babel-plugin-react-remove-properties/pull/3

**Comment by oliviertassinari** [comment]
The test suite still need to be improved

**Comment by oliviertassinari** [comment]
@ovaris I have publish v0.2.0 that support babel6.
